name: "Build StreamDeck App"
description: "Compile your StreamDeck to publish it!"
author: "@SantiMA10"
branding:
  icon: check
  color: purple
inputs:
  input-directory:
    description: "Where is your code"
    required: true
  output-directory:
    description: "Where you want the .streamDeckPlugin"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ github.workspace }}${{ inputs.input-directory }}
    - ${{ github.workspace }}${{ inputs.output-directory }}
